using System;
using CommonInterFacesDD;
namespace StatBlockCommon
{
    public interface IMonsterStatBlock
    {
        string AbilityScore_Mods { get; set; }
        string AbilityScores { get; set; }
        string AC { get; set; }
        string AC_Mods { get; set; }
        string AdditionalExtractsKnown { get; set; }
        string AgeCategory { get; set; }
        string Alignment { get; set; }
        string AlternateNameForm { get; set; }
        string Aura { get; set; }
        string BaseAtk { get; set; }
        string BaseStatistics { get; set; }
        string BeforeCombat { get; set; }
        string Bloodline { get; set; }
        bool Burrow { get; set; }
        bool CharacterFlag { get; set; }
        string Class { get; set; }
        string ClassArchetypes { get; set; }
        bool Climb { get; set; }
        string CMB { get; set; }
        string CMD { get; set; }
        int? CompanionFamiliarLink { get; set; }
        bool CompanionFlag { get; set; }
        string CR { get; set; }
        string DefensiveAbilities { get; set; }
        string Description { get; set; }
        string Description_Visual { get; set; }
        bool DontUseRacialHD { get; set; }
        string DR { get; set; }
        string DuringCombat { get; set; }
        string Environment { get; set; }
        string ExtractsPrepared { get; set; }
        string Feats { get; set; }
        bool Fly { get; set; }
        string FocusedSchool { get; set; }
        string Fort { get; set; }
        string FullText { get; set; }
        string Gear { get; set; }
        string Gender { get; set; }
        string Group { get; set; }
        string HD { get; set; }
        string HP { get; set; }
        string HP_Mods { get; set; }
        int id { get; set; }
        string Immune { get; set; }
        string Init { get; set; }
        bool? IsTemplate { get; set; }
        bool Land { get; set; }
        string Languages { get; set; }
        string LinkText { get; set; }
        string Melee { get; set; }
        string MonsterSource { get; set; }
        string Morale { get; set; }
        int MR { get; set; }
        int MT { get; set; }
        string Mystery { get; set; }
        bool Mythic { get; set; }
        string name { get; set; }
        string Note { get; set; }
        string OffenseNote { get; set; }
        string Organization { get; set; }
        string OtherGear { get; set; }
        string Patron { get; set; }
        string ProhibitedSchools { get; set; }
        string Race { get; set; }
        string RacialMods { get; set; }
        string Ranged { get; set; }
        string Reach { get; set; }
        string Ref { get; set; }
        string Resist { get; set; }
        string Save_Mods { get; set; }
        string Saves { get; set; }
        string Senses { get; set; }
        string Size { get; set; }
        string Skills { get; set; }
        string Source { get; set; }
        string Space { get; set; }
        string SpecialAbilities { get; set; }
        string SpecialAttacks { get; set; }
        string Speed { get; set; }
        string Speed_Mod { get; set; }
        string SpellDomains { get; set; }
        string SpellLikeAbilities { get; set; }
        string SpellsKnown { get; set; }
        string SpellsPrepared { get; set; }
        string SQ { get; set; }
        string SR { get; set; }
        string SubType { get; set; }
        bool Swim { get; set; }
        string TemplatesApplied { get; set; }
        string ThassilonianSpecialization { get; set; }
        string Traits { get; set; }
        string Treasure { get; set; }
        string Type { get; set; }
        bool UniqueMonster { get; set; }
        bool Variant { get; set; }
        string VariantParent { get; set; }
        string Vulnerability { get; set; }
        string Weaknesses { get; set; }
        string Will { get; set; }
        string XP { get; set; }
    }
}
